# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class HetznerInfraCosts < Formula
  desc "Estimate Hetzner Cloud infrastructure costs from Terraform plans"
  homepage "https://github.com/prenansantana/hetzner-infra-costs"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/prenansantana/hetzner-infra-costs/releases/download/v0.1.0/hetzner-infra-costs_0.1.0_darwin_amd64.tar.gz"
      sha256 "c32223479ef5752473d10f95c2595e00ddc7ea11e8efeb60cd4bc66f9af8693b"

      define_method(:install) do
        bin.install "hetzner-infra-costs"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/prenansantana/hetzner-infra-costs/releases/download/v0.1.0/hetzner-infra-costs_0.1.0_darwin_arm64.tar.gz"
      sha256 "9c72d7d776d55b0c1714e8f28c2bd048608943b5c55c5daae06678ede828d430"

      define_method(:install) do
        bin.install "hetzner-infra-costs"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/prenansantana/hetzner-infra-costs/releases/download/v0.1.0/hetzner-infra-costs_0.1.0_linux_amd64.tar.gz"
      sha256 "405bb9278eee66004d10d3e24e779e956879165ca30250b69afd15d9204ccd5b"
      define_method(:install) do
        bin.install "hetzner-infra-costs"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/prenansantana/hetzner-infra-costs/releases/download/v0.1.0/hetzner-infra-costs_0.1.0_linux_arm64.tar.gz"
      sha256 "e1ac8be021ce2a7d11f71449fb64c5289c1482b596f9007d682c3535a98839a9"
      define_method(:install) do
        bin.install "hetzner-infra-costs"
      end
    end
  end

  test do
    system "#{bin}/hetzner-infra-costs", "--version"
  end
end
