# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MgcInfraCosts < Formula
  desc "Estimativa de custos de infraestrutura Magalu Cloud a partir de planos Terraform"
  homepage "https://github.com/prenansantana/mgc-infra-costs"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/prenansantana/mgc-infra-costs/releases/download/v0.1.0/mgc-infra-costs_0.1.0_darwin_amd64.tar.gz"
      sha256 "d99921c3fced9a520db1db03d14aa998bbe302f7a725d52e09e5076fea98e23b"

      define_method(:install) do
        bin.install "mgc-infra-costs"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/prenansantana/mgc-infra-costs/releases/download/v0.1.0/mgc-infra-costs_0.1.0_darwin_arm64.tar.gz"
      sha256 "ff3f43b4eebdce66d5b7175655170b97a168b9be54c92fcb93db659a2f083e66"

      define_method(:install) do
        bin.install "mgc-infra-costs"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/prenansantana/mgc-infra-costs/releases/download/v0.1.0/mgc-infra-costs_0.1.0_linux_amd64.tar.gz"
      sha256 "ceb7c585870830eaaa9f7aa8f754165ae85449ad172129140a1029a67f3975ab"
      define_method(:install) do
        bin.install "mgc-infra-costs"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/prenansantana/mgc-infra-costs/releases/download/v0.1.0/mgc-infra-costs_0.1.0_linux_arm64.tar.gz"
      sha256 "030d6fe6cf3dc61e58c205dc6f71dba52bfd6a73fe71dd21b4bbf50e55596519"
      define_method(:install) do
        bin.install "mgc-infra-costs"
      end
    end
  end

  test do
    system "#{bin}/mgc-infra-costs", "--version"
  end
end
